spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/blog
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret: Proin0viverra0nisl0vitae0mattis0dignissim10Praesent0quis0lectus1
      prefix: "Bearer "
      access:
        expiretion-time: 1
      refresh:
        expiration-time: 36